apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.14.3
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: values.yaml

patches:
  - path: patches/ingress-annotations.yaml
