# Values for ingress-nginx Helm chart
# https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
#
# Customize as needed for your environment (e.g. service type, replicas, tolerations).

controller:
  # service:
  #   type: LoadBalancer  # NodePort or LoadBalancer for cloud
  # replicaCount: 1
  # tolerations: []
  # affinity: {}

  # Use the default ingressClass name "nginx" so overlay INGRESS_CLASS replacement works
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
