apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-silo-wl
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: silo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: silo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: silo
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: silo
          image: artifacts.plane.so/makeplane/silo-commercial:v2.3.3
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: plane-app-vars
            - secretRef:
                name: plane-app-secrets
            - secretRef:
                name: plane-silo-secrets
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 1000Mi
              cpu: 500m
