apiVersion: v1
kind: Service
metadata:
  name: plane-rabbitmq
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: management
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: rabbitmq
