apiVersion: v1
kind: Service
metadata:
  name: plane-opensearch
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: opensearch
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: performance
      port: 9600
      protocol: TCP
      targetPort: 9600
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: opensearch
