apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: plane-live-secrets
  namespace: plane
stringData:
  LIVE_SERVER_SECRET_KEY: "htbqvBJAgpm9bzvf3r4urJer0ENReatceh"
  REDIS_URL: ""  # Will be filled by redis component
