apiVersion: v1
kind: ConfigMap
metadata:
  name: plane-silo-vars
  namespace: plane
data:
  PORT: "3000"
  BATCH_SIZE: "100"
  MQ_PREFETCH_COUNT: "1"
  REQUEST_INTERVAL: "400"
  SILO_BASE_PATH: "/silo"

  CORS_ALLOWED_ORIGINS: "*"

  APP_BASE_URL: "https://plane.example.com"
  API_BASE_URL: "http://plane-api:8000/"
  SILO_API_BASE_URL: "https://plane.example.com"

  PAYMENT_SERVER_BASE_URL: "http://plane-monitor:8080/"
  FEATURE_FLAG_SERVER_BASE_URL: "http://plane-monitor:8080/"

  SENTRY_DSN: ""
  SENTRY_ENVIRONMENT: "production"
  SENTRY_TRACES_SAMPLE_RATE: "0.1"
