apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: plane-silo-secrets
  namespace: plane
stringData:
  # Silo connector credentials (optional service)
  # Will be filled when silo component is enabled
  SILO_HMAC_SECRET_KEY: "gzb7MRLr0FoN129NyWARZEs84P9LzQ"
  SILO_AES_SECRET_KEY: "dsOdt7YrvxsTIFJ37pOaEVvLxN8KGBCr"
  DATABASE_URL: ""
  REDIS_URL: ""
  AMQP_URL: ""

  SLACK_CLIENT_ID: ""
  SLACK_CLIENT_SECRET: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GITHUB_PRIVATE_KEY: ""
  GITHUB_APP_NAME: ""
  GITHUB_APP_ID: ""

  GITLAB_CLIENT_SECRET: ""
  GITLAB_CLIENT_ID: ""

