apiVersion: v1
kind: Secret
metadata:
  name: plane-doc-store-secrets
  namespace: plane
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: password
  AWS_S3_ENDPOINT_URL: http://plane-minio:9000
  AWS_S3_BUCKET_NAME: uploads
  AWS_REGION: us-east-1
  USE_MINIO: "1"
