apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plane-ingress
  namespace: plane
spec:
  rules:
    - host: plane.example.com
      http:
        paths:
          - path: /silo/
            pathType: Prefix
            backend:
              service:
                name: plane-silo
                port:
                  number: 3000
