apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - service-account.yaml

helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 1.7.2
    releaseName: aws-load-balancer-controller
    namespace: kube-system
    valuesFile: values.yaml

patches:
  - path: patches/ingress-annotations.yaml
